# Generated by Django 4.0.5 on 2022-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_months_statistics_accounts_statistics_accounts_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics_voucher_register',
            name='Voucher2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
