# Generated by Django 4.0.5 on 2022-10-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tally_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics_voucher_register',
            name='Particulars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tally_ledger'),
        ),
        migrations.AlterField(
            model_name='tally_ledger',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tally_ledger',
            name='mname',
            field=models.CharField(max_length=255, null=0),
        ),
    ]
